### PR TITLE
Support flake8 6.0

### PR DESCRIPTION
**Pull request by danyeaw**
This PR updates dependencies to support flake8 >= 6.0:
- Drops support for Python 3.7, adds support for Python 3.11
- Drops support for flake8-quotes since it isn't yet compatible
- Upgrades the other dependencies to their latest versions
- Bumps the version of flake8-eradicate to 1.5.0

### CODE REVIEW

**Comment by danyeaw** [comment]
Hi, could someone please approve at least the workflow run? :+1:

**Comment by janmayer** [comment]
Hi @sobolevn, could you have a look at this if you can spare some time?

**Comment by finswimmer** [comment]
bump :smiley:

**Comment by doctrino** [comment]
Any progress on this one? I really appreciate this plugin, but I am forced to update flake8 and will then lose this one.

**Pull request closed without merging**
